[package]
name = "nuhxboard"
version = "0.6.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Devin Droddy <devin.droddy@gmail.com>"]
description = "A cross-platform alternative to NohBoard"
repository = "https://github.com/justDeeevin/NuhxBoard"
keywords = ["keyboard", "virtual", "overlay", "linux", "nohboard"]
categories = ["visualization"]
readme = "README.md"
rust-version = "1.72.0"
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "NuhxBoard.png"]

[package.metadata.wix]
upgrade-guid = "531C0F4B-FFE1-4F4C-BD42-A8449DB1E0BD"
path-guid = "6BCE453A-D71C-4EF5-A85D-B4A43D72A35F"
license = false
eula = false

[dependencies]
async-std = "1.12.0"
color-eyre = { version = "0.6.2", default-features = false }
colorgrad = "0.6.2"
futures = "0.3.30"
home = "0.5.9"
iced = { version = "0.12.0", features = [
  "image",
  "canvas",
  "advanced",
  "async-std",
  "multi-window",
] }
image = { version = "0.24.8", features = ["ico"] }
iced_aw = { version = "0.8.0", features = ["selection_list", "number_input"] }
rdev = "0.5.3"
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
reqwest = { version = "0.11.24", features = ["blocking"] }
display-info = "0.4.8"
geo = "0.28.0"
zip = "0.6.6"

[target.'cfg(windows)'.dependencies]
mslnk = "0.1.8"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.10.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "plan"

[workspace.metadata.dist.dependencies.apt]
libxi-dev = '*'
libxtst-dev = '*'
