[package]
name = "nuhxboard"
description = "Cross-platform input visualizer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
exclude = [
  "keyboards",
  ".github",
  "NuhxBoard.xcf",
  "README.adoc",
  "deny.toml",
  "dist-workspace.toml",
  "flake.*",
  "justfile",
  "keyboards.zip",
  "media",
  "schemas",
  "wix",
  "CHANGELOG.md",
  "KEYCODES.adoc",
]

[package.metadata.wix]
upgrade-guid = "531C0F4B-FFE1-4F4C-BD42-A8449DB1E0BD"
path-guid = "6BCE453A-D71C-4EF5-A85D-B4A43D72A35F"
license = false
eula = false

[dependencies]
iced-multi-window = "1.1.0"
async-std = "1.13.0"
color-eyre = { version = "0.6.3", default-features = false }
colorgrad = "0.7.0"
display-info.workspace = true
eyre = "0.6.12"
futures.workspace = true
geo.workspace = true
home = "0.5.9"
iced = { workspace = true, features = [
  "image",
  "canvas",
  "advanced",
  "async-std",
] }
iced_aw = "0.11.0"
image = { version = "0.25.2", features = ["ico"] }
reqwest = { version = "0.12.7", features = ["blocking"] }
serde_json.workspace = true
zip = "2.2.0"
iced_fonts = "0.1.1"
nuhxboard-types = { path = "crates/types", version = "0.6.0" }
nuhxboard-logic = { path = "crates/logic", version = "0.6.0" }
rdev.workspace = true
nalgebra = "0.33.0"

[build-dependencies]
schemars.workspace = true
nuhxboard-types = { path = "crates/types", version = "0.6.0" }
serde_json = "1.0.128"

[features]
grab = ["nuhxboard-logic/grab"]
debug = ["iced/debug"]

[workspace]
resolver = "2"
members = ["crates/logic", "crates/types"]

[workspace.package]
version = "0.7.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Devin Droddy <devin.droddy@gmail.com>"]
repository = "https://github.com/justDeeevin/NuhxBoard"
keywords = ["keyboard", "streaming", "overlay", "linux", "nohboard"]
categories = ["visualization"]

[workspace.dependencies]
geo = "0.29.3"
iced = "0.13.1"
serde_json = "1.0.133"
futures = "0.3.31"
rdev = "0.5.3"
display-info = "0.5.2"
schemars = "0.8.21"
# rust-version = "1.72.0"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
