[package]
name = "logic"
description = "Input listener for NuhxBoard"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
futures.workspace = true
iced.workspace = true
rdev.workspace = true

[features]
grab = ["rdev/unstable_grab"]
