[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
display-info = "0.5.1"
geo = "0.28.0"
iced = "0.13.1"
schemars = "0.8.21"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
