[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
display-info.workspace = true
geo.workspace = true
iced.workspace = true
ordered-float = "4.6.0"
schemars.workspace = true
serde = { version = "1.0.210", features = ["derive"] }
serde_json.workspace = true
